on:
  push:
    branches:
    - master
name: Docker build
jobs:
  release:
    name: Autotag
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: autotag
        id: autotag
        uses: butlerlogic/action-autotag@1.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_message: ${{ github.event.head_commit.message }}
      - name: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@latest
        if: success()
        with:
          tag_name: ${{steps.autotag.outputs.tagname}}
          release_name: ${{steps.autotag.outputs.tagname}}
          body: ${{steps.autotag.outputs.tagmessage}}
          draft: false
          prerelease: false
